---

- name: main.yml | All roles
  hosts: mac
  sudo: True

  pre_tasks:
    - debug:
        msg=Use Ansible to provision Mac for development.

    - debug:
        msg=Configuring Mac {{ lookup('env', 'HOST') }} as User {{ lookup('env', 'USER') }}.

  roles:
    # - { role: general, tags: ['general'] }
    # - { role: general, when: 'install_general == True' }
    - role: general
    - {role: osxlockdown, when: 'osxlockdown_install == True'}
    - role: python
    - role: ruby
    - role: node
    - role: homebrew
    - role: dotfiles
    - role: git
    - role: mackup
    - role: sublime_text
    # External roles
    - role: zsh
    - role: prezto
