---
- hosts: mac

# Roles
# - General
# - Osxlockdown
# - Python
# - Homebrew
# - Git
# - Mackup
# - Sublime Text

  tasks:

#
### Symlinks
#

    - name: Create home directory symlinks
      file: src={{ item.from }} dest={{ item.to }} state=link
      sudo: True
      with_items:
        - from: ~/Dropbox/mac/bin
          to: ~/bin

#
### Ruby
#

    - name: Install Ruby gems
      gem: name={{ item }} state=latest
      with_items:
        - brewbygems
        - bundler
        - compass
      when: ruby_gems_install == True

# TODO: Run osxdefaults

# TODO: Install zprezto (https://github.com/sorin-ionescu/prezto)
