---
- hosts: mac

# Roles
# - General
# - Osxlockdown
# - Python
# - Ruby
# - Node
# - Homebrew
# - Git
# - Mackup
# - Sublime Text

  tasks:

#
### Symlinks
#

    - name: Create home directory symlinks
      file: src={{ item.from }} dest={{ item.to }} state=link
      sudo: True
      with_items:
        - from: ~/Dropbox/mac/bin
          to: ~/bin

# TODO: Run osxdefaults

# TODO: Install zprezto (https://github.com/sorin-ionescu/prezto)
