---
- hosts: mac
  connection: local
  user: {{ username }}

# Roles
# - General
# - Osxlockdown
# - Python
# - Ruby
# - Node
# - Homebrew
# - Dotfiles
# - Git
# - Mackup
# - Sublime Text
# - Zsh
# - Prezto

  tasks:

#
### Symlinks
#

    - name: Create home directory symlinks
      file: src={{ item.from }} dest={{ item.to }} state=link
      sudo: True
      with_items:
        - from: ~/Dropbox/mac/bin
          to: ~/bin

# TODO: Configure Dotfiles (osxdefaults)

# TODO: Configure Prezto (https://github.com/sorin-ionescu/prezto)
