---
- hosts: mac

# Roles
# - General
# - Osxlockdown
# - Python
# - Homebrew
# - Git
# - Sublime Text

  tasks:

#
# Node.js
#

    - name: Install Node.js
      homebrew:
        name=node
        state=present
        update_homebrew=yes
      when: node_install == True

    - name: Install global apps with npm
      npm:
        name={{ item }}
        global=yes
      with_items:
        - grunt-cli
      when: node_install == True

#
### Symlinks
#

    - name: Create home directory symlinks
      file: src={{ item.from }} dest={{ item.to }} state=link
      sudo: no
      with_items:
        - from: ~/Dropbox/mac/bin
          to: ~/bin

#
### Ruby
#

    - name: Install Ruby gems
      gem: name={{ item }} state=latest
      with_items:
        - brewbygems
        - bundler
        - compass
      when: ruby_gems_install == True

# TODO: Run osxdefaults

#
### Mackup
#

    - name: Run Mackup restore
      command: mackup restore

    - name: Run Mackup backup
      command: mackup backup

    # - name: Create symlink subl for Sublime Text's subl command
    #   file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/subl state=link

# Install zprezto (https://github.com/sorin-ionescu/prezto)