---
# Tasks for Dotfiles role

- name: Clone Dotfiles repository locally
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '{{ dotfiles_repo_path }}'

- name: Run OS X Dotfiles script
  command: ./.osx
