---
# Tasks for General role

- name: Set hostname
  command: scutil --set HostName {{ user_hostname }}
  sudo: True

- name: Install Mac command-line tools (without Xcode)
  command: xcode-select --install
