---
# Tasks for Git role

- name: 'Add Git config file'
  template:
    src=gitconfig.j2
    dest={{ user_home }}/.gitconfig
    owner={{ username }}
    group=staff

- name: Clone Git repositories
  # git clone https://{{ item.url }} {{ item.path }}
  git: >
    repo='https://{{ github_user }}:{{ github_app_token }}@{{ item.url }}.git'
    dest='{{ item.path }}'
    version='master'
    accept_hostkey=True
    update=True
    force=True
  with_items:
    - git_repos
